version: '3.8'

services:
  cisgo-web:
    build: .
    depends_on:
      - cisgo-spaces
    ports:
      - '8000:80'

  cisgo-firebase-admin:
    build:
      context: ./node
    depends_on:
      - cisgo-spaces

  cisgo-spaces:
    build:
      context: ./python
    command: python ./index.py
