version: '3.8'

services:
  cisgo-web:
    build: .
    ports:
      - '8000:80'

  cisgo-spaces:
    build:
      context: ./python
    command: python ./index.py

  cisgo-firebase-admin:
    build:
      context: ./node
    command: node datatree.js
